pipeline{
    agent any
    stages{
      stage('Build'){
          steps{
          echo 'Build Stage'
          }
      }
      stage('Build Command'){
          steps{
          bat 'mvn build'
          }
      }
      stage('Test'){
          steps{
          bat 'mvn test'
          }
      }
    }
}
